import { base4CharToValue, valueToBase4Char } from './base4.js';

/**
 * GF(4) = GF(2)[x] / (x^2 + x + 1), the field with 4 elements {0, 1, α, α+1}.
 * α satisfies α^2 = α + 1, and is a primitive element (α^3 = 1).
 *
 * Elements are represented as 2-bit integers (b1,b0) meaning b1*α + b0*1, which is
 * exactly the base-4 symbol encoding already used elsewhere (A=0, C=1, G=α=2, T=α+1=3).
 * No re-encoding is needed to move between base-4 strings and GF(4) polynomials.
 */
export type GF4 = 0 | 1 | 2 | 3;

/** Addition in GF(2^n) is bitwise XOR (no carries, characteristic 2). */
export function gf4Add(a: GF4, b: GF4): GF4 {
  return (a ^ b) as GF4;
}

// Derived from α^2 = α+1 and α^3 = 1 (GF(4)* is cyclic of order 3, generated by α).
const MUL_TABLE: readonly GF4[][] = [
  [0, 0, 0, 0],
  [0, 1, 2, 3],
  [0, 2, 3, 1],
  [0, 3, 1, 2],
];

export function gf4Mul(a: GF4, b: GF4): GF4 {
  return MUL_TABLE[a][b];
}

export function base4CharToGF4(ch: string): GF4 {
  return base4CharToValue(ch) as GF4;
}

export function gf4ToBase4Char(value: GF4): string {
  return valueToBase4Char(value);
}

/**
 * Fixed, public degree-4 generator polynomial over GF(4): g(x) = x^4 + αx^3 + x^2 + (α+1)x + 1.
 * Coefficients listed highest-to-lowest degree, monic (leading coefficient 1).
 * This is a CRC-style generator, not required to be irreducible (same as standard CRC polynomials).
 */
const GENERATOR: readonly GF4[] = [1, 2, 1, 3, 1];

/** Polynomial long division over GF(4): returns message(x) mod generator(x), as a coefficient array. */
function gf4PolyMod(message: readonly GF4[], generator: readonly GF4[]): GF4[] {
  const degG = generator.length - 1;
  const remainder = message.slice();
  for (let i = 0; i <= remainder.length - generator.length; i++) {
    const factor = remainder[i];
    if (factor !== 0) {
      for (let j = 0; j < generator.length; j++) {
        remainder[i + j] = gf4Add(remainder[i + j], gf4Mul(factor, generator[j]));
      }
    }
  }
  let rem = remainder.slice(Math.max(0, remainder.length - degG));
  while (rem.length < degG) rem.unshift(0);
  return rem;
}

/**
 * The "Complementary Checksum": a CRC-style polynomial-remainder checksum over GF(4),
 * replacing the naive A<->T / C<->G lookup-swap with real Galois Field arithmetic.
 *
 * SECURITY NOTE: this is an error-detection / tamper-evidence checksum, structurally
 * analogous to CRC-32 — it has NO preimage or collision resistance, and a motivated
 * sender can trivially construct a different message with the same checksum. It is
 * suitable for detecting accidental corruption in the "genetic complement" metaphor,
 * not for anything security-relevant. SHA-256 (see src/crypto/hash.ts) remains the
 * only mechanism used for content addressing, Merkle roots, and identity in Helix —
 * this checksum must never be treated as a security boundary.
 */
export function gf4Checksum(base4Message: string): string {
  const coeffs = [...base4Message].map(base4CharToGF4);
  const remainder = gf4PolyMod(coeffs, GENERATOR);
  return remainder.map(gf4ToBase4Char).join('');
}

export function verifyGf4Checksum(base4Message: string, checksum: string): boolean {
  return gf4Checksum(base4Message) === checksum;
}
